Repository uiters/ting-movie, pull requests merged in 2019-04, with the labels that each got.

#20 Complete pagination logic
  package.json
  src/App.js
  src/api/movies.js
  src/components/common/Pagination.js
  src/components/moviesPage/MovieGridItem.js
  src/containers/MoviesPageContainer.js
  src/pages/MoviesPage.js
Labels: new feature

#21 Remove unused images
  public/images/other/actor-img.jpg
  public/images/other/banner-arrow.png
  public/images/other/browser.png
  public/images/other/find-movie.png
  public/images/posters/poster-1.jpg
  public/images/posters/poster-2.jpg
  public/images/posters/poster-3.jpg
  public/images/posters/poster-4.jpg
  public/images/posters/poster-5.jpg
  public/images/posters/poster-6.jpg
  public/images/posters/poster-7.jpg
  public/images/posters/poster-8.jpg
Labels: duplicate

#15 Complete UI for Showtimes page
  package-lock.json
  public/css/bootstrap.min.css
  public/index.html
  src/App.js
  src/__snapshots__/App.test.js.snap
  src/components/index.js
  src/components/showtimesPage/MovieMainInfo.js
  src/components/showtimesPage/MovieShowtimes.js
  src/components/showtimesPage/index.js
  src/pages/HomePage.js
  src/pages/ShowtimesPage.js
  src/pages/index.js
Labels: enhancement

#24 Complete translate language
  package-lock.json
  public/images/blog/bloglist-1.jpg
  public/images/blog/bloglist-2.jpg
  public/images/blog/bloglist-3.jpg
  public/images/movies/upcoming-featured-item.jpg
  public/images/movies/upcoming-item-1.jpg
  public/images/movies/upcoming-item-2.jpg
  public/images/other/features.jpg
  public/images/other/features2.jpg
  public/images/other/home2-bg.jpg
  public/images/other/landscape.jpg
  public/images/other/touchkit.jpg
  public/images/slider/slider1.jpg
  public/images/slider/slider2.jpg
  public/images/slider/slider3.jpg
  public/images/user.png
  src/components/common/Footer.js
  src/components/common/ForgetPassword.js
  src/components/common/HeaderNavigation.js
  src/components/common/MainHeader.js
  src/components/common/SearchForm.js
  src/components/common/SignIn.js
  src/components/common/SignUp.js
  src/components/homePage/Blog.js
  src/components/homePage/Counter.js
  src/components/homePage/LatestMovies.js
  src/components/homePage/Slider.js
  src/components/homePage/Subscribe.js
  src/components/homePage/UpcomingMovies.js
  src/components/moviesPage/Filters.js
  src/components/showtimesPage/MovieMainInfo.js
  src/pages/ContactPage.js
  src/pages/MoviesPage.js
  src/pages/NotFoundPage.js
  src/pages/ShowtimesPage.js
Labels: enhancement

#25 Complete logic for api
  src/api/cinemas.js
  src/api/index.js
  src/api/locations.js
  src/api/movies.js
  src/api/sessions.js
Labels: new feature

#27 Complete logic for movies page
  src/actions/movies.js
  src/components/common/Footer.js
  src/components/common/SearchForm.js
  src/components/moviesPage/MovieGridItem.js
  src/constants/actionTypes/movies.js
  src/containers/MoviesPageContainer.js
  src/pages/MoviesPage.js
  src/reducers/movies.js
Labels: new feature

#30 Complete search for Vietnamese keywords
  .gitignore
  package-lock.json
  package.json
  src/actions/index.js
  src/actions/movies.js
  src/containers/HomePageContainer.js
  src/containers/MoviesPageContainer.js
  src/reducers/movies.js
  yarn.lock
Labels: bug

#32 Fix: the server responded with a status of 404 (Not Found)
  public/css/style.css
  public/index.html
  public/js/custom.js
  public/manifest.json
  public/revolution/css/settings.css
  src/components/homePage/UpcomingMovies.js
Labels: bug

#36 Fix invalid zindex undefined
  src/components/common/Footer.js
  src/pages/ContactPage.js
  src/pages/HomePage.js
  src/pages/MoviesPage.js
  src/pages/NotFoundPage.js
  src/pages/ShowtimesPage.js
  src/utils/loadPackages.js
Labels: enhancement

#43 Complete routes for the movie
  src/App.js
  src/__snapshots__/App.test.js.snap
  src/pages/MoviePage.js
Labels: new feature

#44 Auto focus header section when navigate page
  src/pages/ContactPage.js
  src/pages/HomePage.js
  src/pages/MoviePage.js
  src/pages/NotFoundPage.js
  src/pages/ShowtimesPage.js
  src/pages/index.js
Labels: bug

#45 Fix access control
  package-lock.json
  server/README.md
  server/Request.php
  server/cinemas.php
  server/locations.php
  server/movie.php
  server/movies.php
  server/sessions.php
Labels: enhancement

#47 Complete logic for fetching movie showtimes
  package.json
  src/actions/cinemas.js
  src/actions/common.js
  src/actions/index.js
  src/actions/movie.js
  src/actions/movies.js
  src/actions/sessions.js
  src/api/sessions.js
  src/components/moviePage/MovieShowtimes.js
  src/constants/actionTypes/cinemas.js
  src/constants/actionTypes/common.js
  src/constants/actionTypes/index.js
  src/constants/actionTypes/movie.js
  src/constants/actionTypes/movies.js
  src/constants/actionTypes/sessions.js
  src/containers/MoviePageContainer.js
  src/pages/MoviePage.js
  src/reducers/cinemas.js
  src/reducers/index.js
  src/reducers/movie.js
  src/reducers/movies.js
  src/reducers/sessions.js
  src/styles/MovieShowtimes.css
  yarn.lock
Labels: new feature

#50 Update named routes
  src/components/common/index.js
  src/components/homePage/LatestMovies.js
  src/components/index.js
  src/components/moviePage/MovieShowtimes.js
  src/components/showtimesPage/Pagination.js
  src/components/showtimesPage/index.js
  src/styles/MovieShowtimes.css
Labels: bug

#51 Update API sources
  package-lock.json
  package.json
  server/README.md
  src/api/cinemas.js
  src/api/locations.js
  src/api/movie.js
  src/api/movies.js
  src/api/sessions.js
Labels: enhancement

#55 Update contributors
  .all-contributorsrc
  README.md
  package.json
  yarn.lock
Labels: new feature

#58 Complete update uid package
  package-lock.json
  package.json
  src/components/common/MovieGridItem.js
  src/components/moviePage/MovieShowtimes.js
Labels: enhancement

#60 Complete get movies coming
  server/README.md
  server/movies-coming.php
Labels: enhancement

#61 Complete display coming soon movies
  README.md
  package-lock.json
  package.json
  src/actions/comingMovies.js
  src/actions/index.js
  src/api/comingMovies.js
  src/api/index.js
  src/constants/actionTypes/comingMovies.js
  src/constants/actionTypes/index.js
  src/containers/ShowtimesPageContainer.js
  src/pages/ShowtimesPage.js
  src/reducers/comingMovies.js
  src/reducers/index.js
  src/styles/ShowtimesPage.css
  yarn.lock
Labels: new feature
